esphome:
  name: "ir"
  friendly_name: IR

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+BuEmbUhH9y7Z4ZoRvIQ9lurc+jYvDG4UKCSvFwz8ow="

ota:
  - platform: esphome
    password: "1da784568bd93567a4946a069fc8038a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "IR Fallback Hotspot"
    password: "35lV2Jl9hTbx"

captive_portal:
    
remote_receiver:
  pin: 
    number: GPIO14
    inverted: true
  dump: all

remote_transmitter:
  pin: GPIO4
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%
